# Generated by Django 5.2.17 on 2026-09-30 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.IntegerField(primary_key=True, serialize=False)),
                ("prod_name", models.CharField(max_length=200)),
                ("product_type", models.CharField(db_index=True, max_length=80)),
                ("product_group", models.CharField(db_index=True, max_length=80)),
                ("colour", models.CharField(db_index=True, max_length=60)),
                ("department", models.CharField(max_length=120)),
                ("index_group", models.CharField(db_index=True, max_length=60)),
                ("garment_group", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Display price in GBP", max_digits=8
                    ),
                ),
                ("sales_last_4w", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-sales_last_4w", "article_id"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("age", models.PositiveSmallIntegerField(null=True)),
                ("club_member_status", models.CharField(blank=True, max_length=20)),
                ("fashion_news_frequency", models.CharField(blank=True, max_length=20)),
                ("n_purchases", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(db_index=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "channel",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="1 = store, 2 = online"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.article"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="shop.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("impression", "Impression"),
                            ("click", "Click"),
                            ("add_to_cart", "Add To Cart"),
                            ("purchase", "Purchase"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        blank=True,
                        help_text="feed row or page the item was shown in",
                        max_length=40,
                    ),
                ),
                ("model_version", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.article",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.customer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_type", "placement"],
                        name="shop_event_event_t_2c7f67_idx",
                    )
                ],
            },
        ),
    ]
